# What image do you want to start building on?
FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# What port will the container talk to the outside world with once created?
EXPOSE 5432
